//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Assignments.Models.Assign5
{
    public partial class DepartmentDetails
    {
        public int DepId { get; set; }
        [Required(ErrorMessage = "Department Name is required.")]

        public string DepName { get; set; }
        [Required(ErrorMessage = "Department Location is required.")]
        public string DepLocation { get; set; }
        [Required(ErrorMessage = "Department Employee Count  is required.")]
        public int DepEmpCount { get; set; }
    }
}