//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Assignments.Controllers;
using System.ComponentModel.DataAnnotations;

namespace Assignments.Models.Assign5
{  
    public partial class tblEmployee
    {
        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "Please enter your name")]
        [RegularExpression("^([a-zA-Z '-]+)(?<!\\s)$", ErrorMessage = "Please enter valid Name (Alphabets only)")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Select Gender.")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Please enter your City name")]
        [RegularExpression("^([a-zA-Z '-]+)(?<!\\s)$", ErrorMessage = "Please enter valid City Name (Alphabets only)")]
        public string City { get; set; }

        
       [RemoteClientServer("IsUserEmailAvailable", "Assign11",ErrorMessage ="User with this email already exists")]
        [Required(ErrorMessage = "Email is required.")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Please enter a valid email address")]
        public string EmailId { get; set; }
    }
}
